### ISSUE TITLE
how?

### ISSUE THREAD

**Issue by Wizzardy** [urShadow/Pawn.RakNet#1]
how do you use this to create an anticheat?

**Comment by urShadow** [comment]
Look example "Intercept received player's data" in readme.

**Comment by Wizzardy** [comment]
I still couldn't create anything , the example didn't help at all.

**Comment by urShadow** [comment]
This plugin is designed for those who are familiar with the RakNet and BitStream. You should look at a source code of RakSAMP.

**Comment by Wizzardy** [comment]
I learn fast , so a simple example would help.

**Comment by katursis** [comment]
https://github.com/urShadow/Pawn.RakNet/wiki
