### ISSUE TITLE
SendBulletData() ?

### ISSUE THREAD

**Issue by d4rkuzs** [urShadow/Pawn.RakNet#4]
Hello, is possible to make a SendBulletData function using this plugin?

I was trying to do it by myself but I'm not sure if Im doing it well..

Here's what I have... (incomplete, of course, I was trying to do it following the YSF plugin by Kurta99...)

```
stock SendBulletData(target_id, Float:x,Float:y,Float:z, weaponid)
{


  BS_WriteValue(bs,
                    RNM_INT16, target_id,
                    RNM_CFLOAT, x,
					RNM_CFLOAT, y,
					RNM_CFLOAT, z,
					RNM_UINT8, weaponid);

  new BitStream:bs = BS_New(), RPC_BULLET = 206;

  BS_WriteValue(bs, RNM_UINT8, ID_CONNECTION_LOST);

  BS_Send(bs, player_id);
  BS_Send(bs, -1, PacketPriority:priority = HIGH_PRIORITY, PacketReliability:reliability = RELIABLE_ORDERED);

  BS_Delete(bs);
  //BS_Send(BitStream:bs, player_id, PacketPriority:priority = HIGH_PRIORITY, PacketReliability:reliability = RELIABLE_ORDERED);
  //CSAMPFunctions::Send(&bs, HIGH_PRIORITY, RELIABLE_ORDERED, 0, CSAMPFunctions::GetPlayerIDFromIndex(forplayerid), false);
}
```

**Comment by d4rkuzs** [comment]
Finally, I think what I did it! but it doesn't work with rocket laucher, why? I need to use a different RPC id ? 206 doesn't work

**Comment by katursis** [comment]
https://github.com/urShadow/Pawn.RakNet/wiki/Send-bullet-data

**Comment by ghost** [comment]
I think the time has arrived, when I should remove these functions from YSF. If you could made an example how to disable sync of given keypress, then I will sure remove these funcs from ysf.

**Comment by katursis** [comment]
https://github.com/urShadow/Pawn.RakNet/wiki/SetPlayerDisableKeysSync

**Comment by ghost** [comment]
Very good! Thanks :)
